# Generated by Django 5.2.9 on 2025-12-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didacta', 'adicionar_tema_filme_alterar_genero_notificacao_e_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acesso_provisorio_expira',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que o acesso provisório expira (1 hora após uso do código temporário)', null=True, verbose_name='Expiração do Acesso Provisório'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verificado',
            field=models.BooleanField(default=False, verbose_name='Email Verificado'),
        ),
    ]
